#!/bin/bash
# blocklist-update.sh
# Fetches known scanner/threat-intel IP ranges and writes them as nginx
# "deny" directives to BLOCKLIST_FILE.
#
# Sources:
#   • Firehol Level-1  — highest-confidence malicious IPs and CIDRs
#   • Ipsum             — aggregated threat intelligence (score >= 3)

set -euo pipefail

BLOCKLIST_FILE="${BLOCKLIST_FILE:-/etc/nginx/blocklist.conf}"
TMP_FILE=$(mktemp /tmp/nysm_blocklist.XXXXXX)

log() { echo "[blocklist] $*"; }

cleanup() { rm -f "$TMP_FILE"; }
trap cleanup EXIT

# ─── Write header ─────────────────────────────────────────────────────────────
cat > "$TMP_FILE" << EOF
# NYSM auto-generated blocklist
# Updated: $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# Do not edit manually — regenerated by blocklist-update.sh
# Sources: Firehol Level-1, Ipsum (score >= 3)

EOF

# ─── Helper ──────────────────────────────────────────────────────────────────
# Fetches a URL and appends "deny <ip>;" lines to TMP_FILE.
# Returns 0 on success, 1 on fetch failure (non-fatal).
fetch_and_deny() {
  local url=$1
  local filter_cmd=${2:-"cat"}

  log "Fetching $(basename "$url")..."

  # BUG FIX: DENY_COUNT was incremented inside a pipe subshell, so changes
  # were invisible to the parent. The ((0)) expression also exits non-zero
  # under set -e. Fixed by removing the counter from the subshell entirely
  # and counting lines in the output file after writing (see end of script).
  local tmp_fetch
  tmp_fetch=$(mktemp /tmp/nysm_fetch.XXXXXX)

  if curl -sf --max-time 60 --retry 2 --retry-delay 3 "$url" \
       > "$tmp_fetch" 2>/dev/null; then

    grep -v '^#' "$tmp_fetch" \
      | grep -v '^$'          \
      | eval "$filter_cmd"    \
      | awk '{print $1}'      \
      | grep -E '^[0-9]'      \
      | sed 's/$/;/'          \
      | sed 's/^/deny /'      \
      >> "$TMP_FILE" || true

  else
    log "WARNING: failed to fetch $url — skipping."
    rm -f "$tmp_fetch"
    return 1
  fi

  rm -f "$tmp_fetch"
}

# ─── Sources ──────────────────────────────────────────────────────────────────
fetch_and_deny \
  "https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/firehol_level1.netset"

fetch_and_deny \
  "https://raw.githubusercontent.com/stamparm/ipsum/master/ipsum.txt" \
  "awk '\$2 >= 3 {print \$1}'" || true   # non-fatal if this source is unavailable

# ─── Finalize ─────────────────────────────────────────────────────────────────
echo "" >> "$TMP_FILE"
echo "# allow all others" >> "$TMP_FILE"

mv "$TMP_FILE" "$BLOCKLIST_FILE"
chmod 640 "$BLOCKLIST_FILE"

# BUG FIX: Count deny lines in the written file, not in the subshell.
# This gives the correct count regardless of pipe/subshell scoping.
DENY_COUNT=$(grep -c "^deny " "$BLOCKLIST_FILE" 2>/dev/null || echo 0)
log "Blocklist written to $BLOCKLIST_FILE ($DENY_COUNT entries)"
