# profiles/example.conf
# Copy and rename this file to <your-domain>.conf.
# Load it from the NYSM menu: "Load Profile"

domain_name=updates.example.com
c2_server=10.0.0.1:443
ua_pattern=Mozilla/5\.0.*Windows NT
use_https_upstream=1
